//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJoelGramajoPrueba2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> ProID { get; set; }
        public string paymentType { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
